A (*) denotes where two authors contributed equally.<br /><br />
<table class="years"><tr><td>MacLeod, B. P.*, <b>Parlane, F. G. L.*</b>, & Berlinguette, C. P. How to build an effective self-driving laboratory. <i>Invited submission: MRS Bulletin. Under review</i> (2022).</td></tr>	<tr><td> MacLeod, B. P.*, <b>Parlane, F. G. L.*</b>, Brown, A. K., Hein, J. E., & Berlinguette, C. P. <a href="https://www.degruyter.com/document/doi/10.1515/9783110738087-004/html" target="_blank">Flexible automation for self-driving laboratories.</a> <i>Accelerated Materials Discovery (De Gruyter)</i> <b>4</b>, 105-122 (2022).</td></tr>
	<tr><td> MacLeod, B. P.*, <b>Parlane, F. G. L.*</b>, Rupnow, C. C., Dettelbach, K. E., Elliott, M. S., Morrissey, T. D., Haley, T. H., Proskurin, O., Rooney, M. B., Taherimakhsousi, N., Dvorak, D. J., Chiu, H. N., Waizenegger, C. E. B., Ocean, K., Mokhtari, M., & Berlinguette, C. P. <a href="https://www.nature.com/articles/s41467-022-28580-6" target="_blank">A self-driving laboratory advances the Pareto front for material properties.</a> <i>Nat Commun</i> <b>1</b>, 45-51 (2022).</td></tr>
	<tr><td> Huang, A., Delima, R. S., Kim, Y., Lees, E. W., <b>Parlane, F. G. L.</b>, Dvorak, D. J., Rooney, M. B., Jansonius, R. P., Fink, A. G., Zhang, Z., & Berlinguette, C. P. <a href="https://pubs.acs.org/doi/10.1021/jacs.2c03158" target="_blank">Direct H<sub>2</sub>O<sub>2</sub> Synthesis, without H<sub>2</sub> Gas.</a> <i>J. Am. Chem. Soc.</i> <b>32</b>, 14548-14554 (2022).</td></tr>
	<tr><td> MacLeod, B. P., <b>Parlane, F. G. L.</b>, Brown, A. K., Hein, J. E., & Berlinguette, C. P. <a href="https://www.nature.com/articles/s41563-021-01156-3" target="_blank">Flexible automation accelerates materials discovery.</a> <i>Nat. Mater.</i> <b>7</b>, 722-726 (2021).</td></tr>
	<tr><td> Lees, E. W., Mowbray, B. A. W., <b>Parlane, F. G. L.</b>, & Berlinguette, C. P. <a href="https://www.nature.com/articles/s41578-021-00356-2" target="_blank">Gas diffusion electrodes and membranes for CO<sub>2</sub> reduction electrolysers.</a> <i>Nat Rev Mater</i> <b>1</b>, 55-64 (2021).</td></tr>
	<tr><td> MacLeod, B. P.*, <b>Parlane, F. G. L.*</b>, Morrissey, T. D., Häse, F., Roch, L. M., Dettelbach, K. E., Moreira, R., Yunker, L. P. E., Rooney, M. B., Deeth, J. R., Lai, V., Ng, G. J., Situ, H., Zhang, R. H., Elliott, M. S., Haley, T. H., Dvorak, D. J., Aspuru-Guzik, A., Hein, J. E., & Berlinguette, C. P. <a href="https://www.science.org/doi/10.1126/sciadv.aaz8867" target="_blank">Self-driving laboratory for accelerated discovery of thin-film materials.</a> <i>Sci. Adv.</i> <b>20</b>, 853-859 (2020).</td></tr>
	<tr><td> Taherimakhsousi, N., MacLeod, B. P., <b>Parlane, F. G. L.</b>, Morrissey, T. D., Booker, E. P., Dettelbach, K. E., & Berlinguette, C. P. <a href="http://www.nature.com/articles/s41524-020-00380-w" target="_blank">Quantifying defects in thin films using machine vision.</a> <i>npj Comput Mater</i> <b>1</b>, 6060-6064 (2020).</td></tr>
	<tr><td> Suntrup, L., Stein, F., Klein, J., Wilting, A., <b>Parlane, F. G. L.</b>, Brown, C. M., Fiedler, J., Berlinguette, C. P., Siewert, I., & Sarkar, B. <a href="https://pubs.acs.org/doi/10.1021/acs.inorgchem.9b02591" target="_blank">Rhenium Complexes of Pyridyl-Mesoionic Carbenes: Photochemical Properties and Electrocatalytic CO<sub>2</sub> Reduction.</a> <i>Inorg. Chem.</i> <b>7</b>, 4215-4227 (2020).</td></tr>
	<tr><td> Berlinguette, C. P., Chiang, Y., Munday, J. N., Schenkel, T., Fork, D. K., Koningstein, R., & Trevithick, M. D. <a href="http://www.nature.com/articles/s41586-019-1256-6" target="_blank">Revisiting the cold case of cold fusion.</a> <i>Nature</i> <b>7759</b>, 45-51 (2019).</td></tr>
	<tr><td> Carroll, H. K., <b>Parlane, F. G.</b>, Reich, N., Jelier, B. J., & Montgomery, C. D. <a href="https://linkinghub.elsevier.com/retrieve/pii/S0020169317301937" target="_blank">Phosphoramidite complexes of Pd(II), Pt(II) and Rh(I): An effective hydrosilylation catalyst of 1-hexyne and 1-octene.</a> <i>Inorganica Chimica Acta</i> <b>465</b>, 78-83 (2017).</td></tr>
	<tr><td> <b>Parlane, F. G. L.</b>, Mustoe, C., Kellett, C. W., Simon, S. J., Swords, W. B., Meyer, G. J., Kennepohl, P., & Berlinguette, C. P. <a href="http://www.nature.com/articles/s41467-017-01726-7" target="_blank">Spectroscopic detection of halogen bonding resolves dye regeneration in the dye-sensitized solar cell.</a> <i>Nat Commun</i> <b>1</b>, 14548-14554 (2017).</td></tr>
	<tr><td> Hu, K., Blair, A. D., Piechota, E. J., Schauer, P. A., Sampaio, R. N., <b>Parlane, F. G. L.</b>, Meyer, G. J., & Berlinguette, C. P. <a href="http://www.nature.com/articles/nchem.2549" target="_blank">Kinetic pathway for interfacial electron transfer from a semiconductor to a molecule.</a> <i>Nature Chem</i> <b>9</b>, 853-859 (2016).</td></tr>
	<tr><td> Swords, W. B., Simon, S. J. C., <b>Parlane, F. G. L.</b>, Dean, R. K., Kellett, C. W., Hu, K., Meyer, G. J., & Berlinguette, C. P. <a href="https://onlinelibrary.wiley.com/doi/10.1002/ange.201510641" target="_blank">Evidence for Interfacial Halogen Bonding.</a> <i>Angew. Chem.</i> <b>20</b>, 6060-6064 (2016).</td></tr>
	<tr><td> Simon, S. J. C., <b>Parlane, F. G. L.</b>, Swords, W. B., Kellett, C. W., Du, C., Lam, B., Dean, R. K., Hu, K., Meyer, G. J., & Berlinguette, C. P. <a href="https://pubs.acs.org/doi/10.1021/jacs.6b06288" target="_blank">Halogen Bonding Promotes Higher Dye-Sensitized Solar Cell Photovoltages.</a> <i>J. Am. Chem. Soc.</i> <b>33</b>, 10406-10409 (2016).</td></tr>
	<tr><td> Jelier, B. J., Montgomery, C. D., & <b>Parlane, F. G.</b> <a href="https://linkinghub.elsevier.com/retrieve/pii/S002016931400019X" target="_blank">Deprotonation of a hydrophosphorane and synthesis of the Ni(II) metallophosphorane [NiCl{P(OC<sub>6</sub>H<sub>4</sub>N(CH<sub>3</sub>))<sub>2</sub>}(P(CH<sub>3</sub>)<sub>3</sub>)<sub>2</sub>].</a> <i>Inorganica Chimica Acta</i> <b>413</b>, 121-127 (2014).</td></tr>
</table>